name: Update Database

on:
  push:
    branches:
      - main

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download database.db from GitHub
        run: |
          curl -L https://raw.githubusercontent.com/VitaliiTro/SharinghelperBot/main/base_scooters.db --output database.db

      - name: Confirm file is downloaded
        run: |
          ls -lh database.db  # Перевірка, що файл завантажено
